### ISSUE TITLE
About the approaches for face transfer

### ISSUE THREAD

**Issue by zjulzy** [yinanhe/ForgeryNet#10]
Hi, thanks for your great work. I have never heard of the two approaches for face transfer in your dataset (BlendFace and MMreplacement). Can you provide some information about them?

**Comment by yinanhe** [comment]
We detect faces from images in image-origin by RetinaFace [16] for future manipulation. As shown in Fig. 2 in the main paper, in some scenarios, multiple faces co-occur in a single frame, such as “conversation between two or more people” or “crowd gathering”. To determine the target face for forgery, we ﬁrst use a simple IoU (Intersection-over-Union) based tracking to acquire face tubes each with faces of the same person identity. We select the face which appears most frequently in the video, i.e. has the longest face tube.

**Comment by yinanhe** [comment]
`BlendFace` is a image processing method.  `MMreplacement` is a graphics method with 3d morphable face models. Details are described in Fig.4

**Comment by zjulzy** [comment]
Thank you very much!
