### ISSUE TITLE
GT for Spatial Forgery Localization

### ISSUE THREAD

**Issue by HighwayWu** [yinanhe/ForgeryNet#12]
Hi, thanks for your sharing dataset. May I ask why the GT for Spatial Forgery Localization is not binary (0/1 or 0/255), and the GT is not frame-by-frame. Thanks!

**Comment by yinanhe** [comment]
The value of each pixel in GT can indicate how much it has been changed.  At the same time, you can also easily convert them to 0/255 or 0/1. Thanks.

**Comment by HighwayWu** [comment]
Thanks for your kind reply.
