### ISSUE TITLE
how to get the face crop as yours?

### ISSUE THREAD

**Issue by niyunsheng** [yinanhe/ForgeryNet#13]
I want to do some experiment to reproduce the task "Spatial Forgery Localization", but I don't know how to get the same face crop as yours while the face crop area is related to the final IoU results.

**Comment by yinanhe** [comment]
We use `RetinaFace` to detect the face bounding box and use 1.3x bbox to crop the faces. To determine the target face for forgery, we first use a simple IoU (Intersection-over-Union) based tracking to acquire face tubes each with faces of the same person identity. We select the face which appears most frequently in the video, i.e. has the longest face tube.

**Comment by niyunsheng** [comment]
3ks
