### ISSUE TITLE
What "BlendFace" and "MMReplacement" refers to?

### ISSUE THREAD

**Issue by TianyunYoung** [yinanhe/ForgeryNet#15]
Hello! I notice most of the generation methods used in the dataset have details on the internet, but I can find little information about "BlendFace" and "MMReplacement". Are they from academic papers or open software? Or they are methods created by your team? If they are publicly available methods, could you give me a link about the details? Thank you very much!

**Comment by yinanhe** [comment]
"BlendFace" is a image processing method which predicts the masks needs to be replaced, transform and blending . "MMreplacement" is a graphics method with 3d morphable face models. Details are described in Fig.4
