### ISSUE TITLE
Baseline model of Xception download

### ISSUE THREAD

**Issue by yunzaitianshang** [yinanhe/ForgeryNet#18]
I download the model from google drive.When unzipping, a message is displayed indicating that the file is corrupted. Can you give me a new download link? For example, Baidu network disk.

**Comment by yinanhe** [comment]
Baseline model is not compressed by zip.  Use torch to load it.

```
import torch
model = torch.load('ckpt_iter.pth.tar')
```

**Comment by yunzaitianshang** [comment]
thank you.
