### ISSUE TITLE
How do we download the dataset?

### ISSUE THREAD

**Issue by ahaliassos** [yinanhe/ForgeryNet#2]
Hi,

I tried downloading the dataset from here https://yinanhe.github.io/projects/forgerynet.html, but I couldn't find the "Download * Set" button to click. Could you help me out please?

Many thanks!

**Comment by depblack** [comment]
About four days ago, I downloaded the dataset in that URL, 
but today I check , it has gone.
Maybe the datasets has some problem, so the Owner removed the links

**Comment by niyunsheng** [comment]
I have the same question

**Comment by yinanhe** [comment]
Sorry, we have already updated the download link.
