### ISSUE TITLE
tar:Unexpected EOF in archive tar: Error is not recoverable: exiting now

### ISSUE THREAD

**Issue by damengdameng** [yinanhe/ForgeryNet#20]
Hi,I have downloaded the dataset from google drive. But when I tried to unzip the Training.tar.0 by :

`
tar -xvf Training.tar.0
`

the error comes as follow:
`
tar:Unexpected EOF in archive 
tar:Unexpected EOF in archive 
tar: Error is not recoverable: exiting now
`
and when I try to unzip the Training.tar.2:

<img width="727" alt="image" src="https://user-images.githubusercontent.com/35157208/145980696-695454d1-9741-4b29-8698-3d33cbcb2f49.png">

<img width="735" alt="image" src="https://user-images.githubusercontent.com/35157208/145980497-f33867a2-503a-473d-8888-72e526228e99.png">

Why this happened? How could I get the data?
Whether the files in google drive broken or not？ 
Please give me some advice, thank you.

**Comment by yinanhe** [comment]
```
cat Training.tar.* >> Training.tar
tar -xvf Training.tar
tar -xvf Validation.tar
```

**Comment by damengdameng** [comment]
> cat Training.tar.* >> Training.tar
> tar -xvf Training.tar
> tar -xvf Validation.tar

It works! Thank you!
