### ISSUE TITLE
Questions about the approaches in the datasets.

### ISSUE THREAD

**Issue by damengdameng** [yinanhe/ForgeryNet#22]
Hi,i have to say you did a excellent and meaningful work at first! I am really appreciate for your contribution.
There are some questions about the dataset that confused me these days and I really wish to get your help~
1. Since the authors of face shifter/Talking-head Video did not open the source code, how did you use these approaches to generate samples? Did you implement the project by yourself?
2. About the face editing methods you used in the dataset, the open source code of [DiscoFaceGAN](https://github.com/microsoft/DiscoFaceGAN) seems to generate the result images only from the latent features but not from the real image. I wonder did you implement the real-image based DiscoFaceGAN  to edit the original images in the dataset or you just generate the random identity and do  face swap(align - color match - blending) between this and original images?

Waiting for you reply! 
Have a nice day~

**Comment by yinanhe** [comment]
1. Yes, we implement by ourselves.
2. We generate the random identity and do face swap between this and original images.
