### ISSUE TITLE
How can I open Training.tar.4 file?

### ISSUE THREAD

**Issue by inglis92** [yinanhe/ForgeryNet#23]
Hello, you did a great job with Forgerynet. 

I requested and obtained access to the Training folder, I downloaded one of the files contained, but I can't open it because of its extension. "Training.tar.4" for example, how can i open this folder as an ".tar"?

**Comment by yinanhe** [comment]
Hi, There are 5 files in the training set from 0 to 4.  You should gather them together by command following,
```
cat Training.tar.* >> Training.tar
tar-xvf Training.tar
```

**Comment by inglis92** [comment]
Thanks! Following those commands i'll download all the training set? What if i need just a part of them? I am writing my university thesis on ForgeryNet and my teacher told me to download just a part of the whole dataset, but i don't know how...

**Comment by yinanhe** [comment]
Yes, you can unpack the Training.tar.4 by `tar -xvf Training.tar.4`. But as you say, it only has the real part of the whole dataset.

**Comment by inglis92** [comment]
Thanks for the help! 
Just one last question: Where I need to write this commands? I'm sorry if this question may be stupid but it's the first time i approach to a dataset

**Comment by yinanhe** [comment]
In the download path where you save the tar.

**Comment by inglis92** [comment]
I used chrome to download the Training.tar.4 . When I try to download any other Training.tar.* it won't finish beacause of a "forbidden" error in Chrome. Is there a way to download it without using Chrome?  Thanks for patience!

**Comment by yinanhe** [comment]
Maybe you can reference #19
