### ISSUE TITLE
Question about the label

### ISSUE THREAD

**Issue by Elijah-Yi** [yinanhe/ForgeryNet#26]
发现数据集中一些数据标注与标签文件不同。
2 train_video_release/1/987080cdf7ec51e4c46c1055d6cdd0eb/47d69f53ec52643354975550e39130be/video.mp4 79 17 1 96 64 0 1 2 1
在数据集中发现在79帧以前还有一些数据是操纵过了的  但是没有标记，能解释一下数据标注吗？还是训练过程中只用标注过的数据？

**Comment by yinanhe** [comment]
79帧前也会有操纵过的，在task4中只用标注的数据就好

**Comment by Elijah-Yi** [comment]
还有一些数据  帧数和 标签里面的帧数不一致，3 train_video_release/1/ddce53972dcb26bbc448d01e4e833f47/247ced0b1f4a6a9690252569eeda23c5/video.mp4 0 14 0 14 15 1 29 44 0 1 2 1  比如这个  总共有91 帧，但是 29 + 44= 73帧，是不是意味着还有部分数据在73 帧以后？

**Comment by yinanhe** [comment]
是的，因为视频任务也涉及到task3，所以全量帧是给task3准备的。 task4中的数据是视频中的一部分。

**Comment by Elijah-Yi** [comment]
👌🏻 非常感谢
