### ISSUE TITLE
Google drive dataset permission

### ISSUE THREAD

**Issue by twinplant** [yinanhe/ForgeryNet#32]
Hello, I want to use the dataset for deepfake detection. My Gmail id is twinplant7@gmail.com

**Comment by yinanhe** [comment]
https://drive.google.com/drive/folders/1gViqLc4l9sT1WTB-_hlcDUCWYskT2_LE?usp=sharing
https://drive.google.com/file/d/1am20PkJVkKtXJvyH58wLcGoat3zGDudO/view?usp=sharing

**Comment by reallm** [comment]
Failed to get file: googleapi: Error 404: File not found: 1gViqLc4l9sT1WTB-_hlcDUCWYskT2_LE., notFound
