### ISSUE TITLE
Google drive access to dataset

### ISSUE THREAD

**Issue by dragosconst** [yinanhe/ForgeryNet#38]
Hello,

I'd appreciate if you could share your google drive dataset with me, my team and I are working on a Deepfake detection research project. My gmail is tantarudragos@gmail.com . Thank you.

**Comment by yinanhe** [comment]
It has been shared with you : )

**Comment by dragosconst** [comment]
Thank you very much :) . It seems that I do not have access to the Validation set, could you please grant me access to it, too? In case it is private, we could make our own Validation set, we just figured it would be better for testing our method if we used the Validation set provided by you. Thanks again.
