### ISSUE TITLE
Access Permission of Google drive dataset

### ISSUE THREAD

**Issue by haotianll** [yinanhe/ForgeryNet#39]
Hi, I want to download the ForgeryNet dataset for research. 
Could you please give me access permission to the download links? My email address is haotianliu001@gmail.com

**Comment by yinanhe** [comment]
It's already been shared with you. We will handle the mail for the first time on the Chinese workday.

**Comment by haotianll** [comment]
Got it. Thank you so much !

**Comment by liuyuxun12** [comment]
Hi, Can you share data downloadlinks for me ?  My email address is mike_hulove@outlook.com
