### ISSUE TITLE
Access Permission of Google drive dataset

### ISSUE THREAD

**Issue by yspch2022** [yinanhe/ForgeryNet#43]
Hellow, I want to download the ForgeryNet dataset for deepfake detection research.
Could you please give me access permission to the download links? My email address is yspch2022@gmail.com
Thank you~

**Comment by yinanhe** [comment]
Can you access the quark for download this dataset：https://pan.quark.cn/s/d367b4758969

**Comment by gaurisharma360** [comment]
i am also facing the same issue. able to access the link but not able to download dataset. My email is gaurisharma360@gmail.com

**Comment by yinanhe** [comment]
I am glad to tell you that we have put the data under opendatlab, which has more stable global access. You can log in to https://opendatalab.com/OpenDataLab/ForgeryNet through your github account and apply for download. I will receive the application Send you the download link as soon as possible! @yspch2022

**Comment by yspch2022** [comment]
> I am glad to tell you that we have put the data under opendatlab, which has more stable global access. You can log in to https://opendatalab.com/ForgeryNet/download through your github account and apply for download. I will receive the application Send you the download link as soon as possible! @yspch2022

Sorry for the late reply. Let's try it this way.

**Comment by yspch2022** [comment]
> > I am glad to tell you that we have put the data under opendatlab, which has more stable global access. You can log in to https://opendatalab.com/ForgeryNet/download through your github account and apply for download. I will receive the application Send you the download link as soon as possible! @yspch2022
> 
> Sorry for the late reply. Let's try it this way.



> > I am glad to tell you that we have put the data under opendatlab, which has more stable global access. You can log in to https://opendatalab.com/ForgeryNet/download through your github account and apply for download. I will receive the application Send you the download link as soon as possible! @yspch2022
> 
> Sorry for the late reply. Let's try it this way.

Hellow, I finally received all the data. By the way, I think triaing files are divided and compressed, but how do I decompress them? "copy /b Training.tar.0+Training.tar.1+Training.tar.2+Training.tar.3+Training.tar.4" is right?

**Comment by yinanhe** [comment]
You can use `cat Training.tar.* >> Training.tar`

**Comment by vmedappa** [comment]
Hello, thank you for the great work and open sourcing the dataset. I have been trying to access the data using https://opendatalab.com/ForgeryNet/download but it gives me the following error 

<img width="1248" alt="Screen Shot 2023-10-17 at 11 46 25 AM" src="https://github.com/yinanhe/ForgeryNet/assets/40217037/7565494c-d020-4d0c-b7df-fbe52c203fa0">

Please let me know if I can access the data through another method. Using https://pan.quark.cn/s/d367b4758969 is hard because it asks me to download the browser in order to download the files, this is after I figure out how to login to the website.

**Comment by snowstorm1102** [comment]
您好！夸克网盘的文件被删除了，opendatalab上的申请无人回复，如果方便的话可以给我下载链接吗？我的邮箱是568249714@qq.com，十分感谢！！期待您的回复！

**Comment by snowstorm1102** [comment]
> 我很高兴地告诉大家，我们已经将数据放在 opendatlab 下，它拥有更稳定的全球访问。您可以通过 github 帐户登录 https://opendatalab.com/OpenDataLab/ForgeryNet 并申请下载。我会收到申请 尽快将下载链接发送给您！

您好！夸克网盘的文件被删除了，opendatalab上的申请无人回复，如果方便的话可以给我下载链接吗？我的邮箱是 568249714@qq.com，十分感谢！！！
