### ISSUE TITLE
Will the bounding box information be provided?

### ISSUE THREAD

**Issue by XJay18** [yinanhe/ForgeryNet#6]
Hi, thanks for the amazing work! 
I checked several samples of the image subset and found that sometimes there is more than one face in an image. Will you provide the exact face bounding box coordinates for image-level detection? Or could you please provide more information about the face detector you used in this work? Thanks a lot!

**Comment by yinanhe** [comment]
In our paper, we use `RetinaFace` as our face detector.

**Comment by ahaliassos** [comment]
In the paper you state 

"To determine the target face for forgery, we first use a simple IoU (Intersection-over-Union) based tracking to acquire face tubes each with faces of the same person identity. We select the face which appears most frequently in the video, i.e. has the longest face tube."

Could you please provide the code (or more details) for this step? It's quite important to have the correct face boundaries for fair evaluation, and it becomes significantly more complicated when there are multiple faces in a given frame.

Many thanks!

**Comment by yinanhe** [comment]
Sorry, this code will not be provided during the challenge.

**Comment by ahaliassos** [comment]
According to the paper, the longest face tube is selected as the target face. But what happens if two (or more faces) appear in exactly the same number of frames? For example, there are some videos, e.g., showing a conversation, where two faces appear in every frame. Which face is selected in that case?

**Comment by yinanhe** [comment]
In this case, the face with a larger area will be selected.
