### ISSUE TITLE
What types of forgery methods the labels corresponds to?

### ISSUE THREAD

**Issue by TianyunYoung** [yinanhe/ForgeryNet#7]
Hello! In the readme file and training list, I can only get the information about the labels of each class, but I still don't know what types of forgery methods the labels correspond to (e.g., label '1' represents 'FirstOrderMotion' and label '2' represents 'StyleGAN'. ) How can I get these information?

**Comment by yinanhe** [comment]
1: FaceShifter
2: FS-GAN
3: DeepFakes
4: BlendFace
5: MMReplacement
6: DeepFakes-StarGAN-Stack
7: Talking Head  Video
8: ATVG-Net
9: StarGAN-BlendFace-Stack
10: First Order Motion
11: StyleGAN2
12: MaskGAN
13: StarGAN2
14: SC-FEGAN
15: DiscoFaceGAN

**Comment by TianyunYoung** [comment]
Thank you very much!
