### ISSUE TITLE
Many images are abnormal

### ISSUE THREAD

**Issue by neverUseThisName** [yinanhe/ForgeryNet#8]
I see many images are discolored. Is it supposed to look like that?
![frame00019](https://user-images.githubusercontent.com/36028079/127417904-5fab5d20-fd55-4875-bf23-e8a44d4883b0.jpg)
![frame00001](https://user-images.githubusercontent.com/36028079/127417907-bc587e48-d269-42a4-9ca4-391b67307a81.jpg)
![frame00022](https://user-images.githubusercontent.com/36028079/127417911-46055e2c-e79b-46e4-bc33-d349d9994a79.jpg)
![frame00023](https://user-images.githubusercontent.com/36028079/127417912-48afdee0-b088-43c6-98df-833ef5240f2c.jpg)

**Comment by yinanhe** [comment]
It's a kind of perturbation.

**Comment by chenshen03** [comment]
Can you share the perturbation code used for the ForgeryNet dataset?
