### ISSUE TITLE
about your dataset for Image Forgery classification 

### ISSUE THREAD

**Issue by xuanli98** [yinanhe/ForgeryNet#9]
Thanks for your great work. I have some questions about your dataset  for Image Forgery classification. 
Q1: Would you like to tell me if there are multiple faces in a single frame in your training data  for Image Forgery classification ?
Q2: Do some pictures like this have faces? Or is it just one of the perturbations? I find it is just green and blue.
data comes from test data downloaded from https://drive.google.com/file/d/1conYQXWguAwJ1eEwewHyMBGUtgjgR_sM/view?usp=sharing  :f7d916050dfb89147167eabb15124458.jpg, 0c6e1e7d95fe1448c7114bfb46d47ef8.jpg
![0c6e1e7d95fe1448c7114bfb46d47ef8](https://user-images.githubusercontent.com/30352320/128293581-c212eec5-a2db-405a-8341-6f1898064d75.jpg)
![f7d916050dfb89147167eabb15124458](https://user-images.githubusercontent.com/30352320/128294010-27a2efb7-3aa9-416c-9dd3-33ac8e6363df.jpg)

**Comment by yinanhe** [comment]
A1:
We detect faces from images in image-origin by RetinaFace [16] for future manipulation. As shown in Fig. 2 in the main paper, in some scenarios, multiple faces co-occur in a single frame, such as “conversation between two or more people” or “crowd gathering”. To determine the target face for forgery, we ﬁrst use a simple IoU (Intersection-over-Union) based tracking to acquire face tubes each with faces of the same person identity. We select the face which appears most frequently in the video, i.e. has the longest face tube.

A2:
 They are error distortion when extracting frames from video.
